---
- name: Full System Upgrade
  hosts: local
  tasks:
    - name: full pacman update
      pacman: 
        upgrade: yes
        update_cache: yes
      tags: 
      - upgrade

- name: Install Pacaur
  hosts: local
  tasks: 
    - name: installing pacman dependencies
      become: yes
      pacman: 
        name: '{{item}}'
        state: latest
      with_items:
        - binutils
        - gcc
        - expac
        - yajl
        - jq
        - make
        - base-devel
        - git
        - fakechroot
        - gtest
        - meson
      tags:
        - packages
    - name: cloning auracle-git
      ansible.builtin.get_url:
        url: https://aur.archlinux.org/cgit/aur.git/snapshot/auracle-git.tar.gz
        dest: /home/john/ansible_installs/auracle_git 
  
    - name: unpacking auracle-git
      command: chdir=/home/john/ansible_installs/auracle_git tar -xzf auracle-git.tar.gz
    
    - name: making auracle-git
      command: chdir=/home/john/ansible_installs/auracle_git/auracle-git makepkg -f PKGBUILD --noconfirm

    - name: finding auracle-git
      ansible.builtin.find:
        paths: /home/john/ansible_installs/auracle_git/auracle-git
        recurse: yes
        patterns: 'auracle-git-*'
      register: result
    - name: installing auracle-git
      become: yes
      command: chdir=/home/john/ansible_installs/auracle_git/auracle-git pacman -U "{{item.path}}" --noconfirm
      with_items: "{{result.files}}"
    
    - name: cloning pacaur
      git:
        repo: https://aur.archlinux.org/pacaur.git
        dest: /home/john/ansible_installs/pacaur
        clone: yes
        update: yes

    - name: Making pacaur
      command:
        chdir=/home/john/ansible_installs/pacaur makepkg -si --noconfirm
